---
 # Name the current run
 run: image_baseline

 info: | 
     train on images

 # Data stores
 dataset:
     betas_path: "/huge/seagie/data/subj_2/betas_meaned/"
     captions_path: "/huge/seagie/data/subj_2/captions/"
     nsd_dir: "/home/seagie/NSD2"
 log: "./Log/"

 # Training
 epochs: 25
 batch_size: 128
 max_length: 10
 optimizer: Adam
 alpha: 0.001
 decay: 0 #1.0e-4
 dropout_input: 0 # 0.17
 dropout_features: 0 # 0.18
 dropout_text: 0 # 0.01
 dropout_lstm: 0

 input_reg: 0 # 0.002         # scientific notation requires decimal notation - x.0e
 lstm_reg: 0 # 0.0003 
 output_reg: 0 # 1.3e-5

 # Input size
 input: 
     full: 327684
     vc: 62756
     pca: 5000
     mscoco: 4096

 # Model size 
 units: 512
 embedding_dim: 256
 top_k: 5000





