---
 # Name the current run
 run: locally_connected_fixed_guse

 info: | 
     previously forgot to update the guse embeddings with the fixed caption index
     now it should be correct and the model should be able to actually learn proper guse embeddings

 # Data stores
 dataset:
     betas_path: "/fast/seagie/data/subj_2/betas_averaged/"
     captions_path: "/fast/seagie/data/subj_2/captions/"
     nsd_dir: "/home/seagie/NSD2"
 log: "./Log/"

 seed: 42

 # Training
 epochs: 100
 batch_size: 64
 max_length: 10
 optimizer: Adam
 alpha: 0.001
 decay: 0 #1.0e-4

 dropout_input: 0.1 # 0.17
 dropout_features: 0.4 # 0.18
 dropout_text: 0.3 # 0.01
 dropout_lstm: 0.5
 dropout_attn: 0.2

 input_reg: 1.0e-3 # 0.002         # scientific notation requires decimal notation - x.0e
 lstm_reg: 1.0e-3 # 0.0003 
 output_reg: 0 # 1.3e-5

 # Input size
 input: 
     full: 327684
     vc: 62756
     pca: 5000
     mscoco: 4096

 # Model size 
 units: 512 # lstm
 attn_units: 64
 embedding_features: 512
 embedding_text: 512
 top_k: 5000





