---
 # Name the current run
 run: soft_atten_clipnorm_l2_dropout

 info: | 
     Model based on ray-tune with best performing L2, dropout values, plus clipnorm

 # Data stores
 dataset:
     betas_path: "/huge/seagie/data/subj_2/betas_meaned/"
     captions_path: "/huge/seagie/data/subj_2/captions/"
     nsd_dir: "/home/seagie/NSD2"
 log: "./Log/"

 # Training
 epochs: 100
 batch_size: 128
 max_length: 11
 optimizer: Adam
 alpha: 0.001
 decay: 0 #1.0e-4
 dropout_input: 0.17 # 0.25
 dropout_features: 0.18 # 0.05
 dropout_text: 0.01 # 0.35

 input_reg: 0.002 #8.5        # scientific notation requires decimal notation - x.0e
 lstm_reg: 0.0003 #0.005
 output_reg: 1.3e-5 #0.005 # 0.000005

 # Input size
 input: 
     full: 327684
     vc: 62756
     pca: 5000
     mscoco: 4096

 # Model size 
 units: 512
 embedding_dim: 128
 top_k: 5000





